export const FETCH_COINS_LIST_REQUEST = "FETCH_COINS_LIST_REQUEST";
export const FETCH_COINS_LIST_SUCCESS = "FETCH_COINS_LIST_SUCCESS";
export const FETCH_COINS_LIST_ERROR = "FETCH_COINS_LIST_ERROR";

export const FETCH_COINS_DATA_REQUEST = "FETCH_COINS_DATA_REQUEST";
export const FETCH_COINS_DATA_SUCCESS = "FETCH_COINS_DATA_SUCCESS";
export const FETCH_COINS_DATA_ERROR = "FETCH_COINS_DATA_ERROR";

export const FETCH_NEWS_REQUEST = "FETCH_NEWS_REQUEST";
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const FETCH_NEWS_ERROR = "FETCH_NEWS_ERROR";

export const FOLLOW_COIN = "FOLLOW_COIN";
export const UNFOLLOW_COIN = "UNFOLLOW_COIN";
