export const FETCH_COINS_INFO_REQUEST = "FETCH_COINS_INFO_REQUEST";
export const FETCH_COINS_INFO_SUCCESS = "FETCH_COINS_INFO_SUCCESS";
export const FETCH_COINS_INFO_ERROR = "FETCH_COINS_INFO_ERROR";

export const FETCH_COINS_DATA_REQUEST = "FETCH_COINS_DATA_REQUEST";
export const FETCH_COINS_DATA_SUCCESS = "FETCH_COINS_DATA_SUCCESS";
export const FETCH_COINS_DATA_ERROR = "FETCH_COINS_DATA_ERROR";

export const FETCH_NEWS_REQUEST = "FETCH_NEWS_REQUEST";
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const FETCH_NEWS_ERROR = "FETCH_NEWS_ERROR";

export const FETCH_EVENTS_REQUEST = "FETCH_EVENTS_REQUEST";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_ERROR = "FETCH_EVENTS_ERROR";

export const FOLLOW_COIN = "FOLLOW_COIN";
export const UNFOLLOW_COIN = "UNFOLLOW_COIN";

export const SET_EVENT_SEEN = "SET_EVENT_SEEN";
export const SET_THEME = "SET_THEME";
export const SET_BACKGROUND = "SET_BACKGROUND";
export const SET_CUSTOM_BACKGROUND = "SET_CUSTOM_BACKGROUND";

export const TOGGLE_VINTAGE_FONT = "TOGGLE_VINTAGE_FONT";
export const SET_FONT_SIZE = "SET_FONT_SIZE";

export const SET_USER_HOLDINGS = "SET_USER_HOLDINGS";
export const SET_USER_CURRENCY = "SET_USER_CURRENCY";

export const DELETE_USER_HOLDINGS = "DELETE_USER_HOLDINGS";
export const SORT_USER_HOLDINGS = "SORT_USER_HOLDINGS";

export const TOGGLE_SCAN_LINES = "TOGGLE_SCAN_LINES";
export const SET_SCAN_LINES_INTENSITY = "SET_SCAN_LINES_INTENSITY";
